SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `sys_defect_log` MODIFY COLUMN `defect_log_describe` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '缺陷日志的描述';

SET FOREIGN_KEY_CHECKS=1;
